#     _   _                       _          _
#    | | | |_   _ _ __   ___ _ __| | ___  __| | __ _  ___ _ __
#    | |_| | | | | '_ \ / _ \ '__| |/ _ \/ _` |/ _` |/ _ \ '__|
#    |  _  | |_| | |_) |  __/ |  | |  __/ (_| | (_| |  __/ |
#    |_| |_|\__, | .__/ \___|_|  |_|\___|\__,_|\__, |\___|_|
#           |___/|_|                           |___/
#     _____     _          _
#    |  ___|_ _| |__  _ __(_) ___
#    | |_ / _` | '_ \| '__| |/ __|
#    |  _| (_| | |_) | |  | | (__
#    |_|  \__,_|_.__/|_|  |_|\___|
#

version: '2.1'

volumes:
  orderer-vm:
  peer-vm:
  couchdb:
  pgdata:
  walletstore:

networks:
  blockchain-net:

services:


#      ___          _
#     / _ \ _ __ __| | ___ _ __ ___ _ __
#    | | | | '__/ _` |/ _ \ '__/ _ \ '__|
#    | |_| | | | (_| |  __/ | |  __/ |
#     \___/|_|  \__,_|\___|_|  \___|_|

  orderer.example.com:
    container_name: example.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
      - 8443:8443
    volumes:
        - ./config/genesis.block:/var/hyperledger/orderer/genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
        - orderer-vm:/var/hyperledger/production/orderer
    networks:
      - blockchain-net


#    ____
#    |  _ \ ___  ___ _ __
#    | |_) / _ \/ _ \ '__|
#    |  __/  __/  __/ |
#    |_|   \___|\___|_|
#
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.3
    dns_search: .
    environment:
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_CHAINCODE_DEPLOYTIMEOUT=300s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_blockchain-net
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - PEER-CHAINCODEDEV=true
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=DevCouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=Blockchain4ever
      - CORE_METRICS_PROVIDER=prometheus

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/crypto/peer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/crypto/peer/tls
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/crypto/orderer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/users/
        - peer-vm:/var/hyperledger/production
    depends_on:
      - orderer.example.com
      - couchdb
    networks:
      - blockchain-net


#       ____                 _     ____  ____
#      / ___|___  _   _  ___| |__ |  _ \| __ )
#     | |   / _ \| | | |/ __| '_ \| | | |  _ \
#     | |__| (_) | |_| | (__| | | | |_| | |_) |
#      \____\___/ \__,_|\___|_| |_|____/|____/


  #http://127.0.0.1:5984/_utils/#login
  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:0.4
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=DevCouchDB
      - COUCHDB_PASSWORD=Blockchain4ever
    ports:
      - 5984:5984
    volumes:
        - couchdb:/opt/couchdb/data
    networks:
      - blockchain-net

#     ____ _     ___
#    / ___| |   |_ _|
#   | |   | |    | |
#   | |___| |___ | |
#    \____|_____|___|

  cli-network:
    container_name: cli-network
    image: hyperledger/fabric-tools:2.3
    tty: true
    # dns_search: .
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - FABRIC_CFG_PATH=/var/hyperledger/config
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ./config/:/etc/hyperledger/channel/
        - ./chaincode:/chaincode
        - ../../:/git
        - ./core/:/var/hyperledger/config
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/crypto/orderer/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/crypto/peer/tls
    cap_add:
        - SYS_PTRACE
    security_opt:
        - seccomp:unconfined

    networks:
      - blockchain-net
    # depends_on:
    #   - orderer.example.com
    #   - peer0.org1.example.com
    #   - couchdb



#    _____            _
#   | ____|_  ___ __ | | ___  _ __ ___ _ __
#   |  _| \ \/ / '_ \| |/ _ \| '__/ _ \ '__|
#   | |___ >  <| |_) | | (_) | | |  __/ |
#   |_____/_/\_\ .__/|_|\___/|_|  \___|_|
#              |_|

  explorerdb.example.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.example.com
    hostname: explorerdb.example.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blockchain-net
    depends_on:
        - orderer.example.com
        - peer0.org1.example.com
        - couchdb

  explorer.example.com:
    image: hyperledger/explorer:latest
    container_name: explorer.example.com
    hostname: explorer.example.com
    environment:
      - DATABASE_HOST=explorerdb.example.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8081:8080
    depends_on:
      explorerdb.example.com:
        condition: service_healthy
    networks:
      - blockchain-net

